import type { CaptionPreset, CaptionSettings, CaptionStyle } from "@/types";

export const DEFAULT_CAPTION_SETTINGS: CaptionSettings = {
  chunking: "medium",
  minWordsPerCaption: 4,
  maxWordsPerCaption: 7,
};

const base: Omit<CaptionStyle, "presetId"> = {
  fontFamily: "Inter",
  fontWeight: "bold",
  fontSize: 72,
  textAlign: "center",
  textColor: "#FFFFFF",
  highlightColor: "#FFD400",
  stroke: "medium",
  shadow: true,
  background: "none",
  textCase: "original",
  position: "bottom-center",
  animation: "pop",
  wordHighlightEnabled: false,
  decoration: "none",
  layout: "inline",
};

// 20 visually distinct themes across the categories called for in the spec
// (minimal / bold / kinetic / editorial / business / creator / tamil). Each
// varies font pairing, hierarchy (via case/weight/size), color treatment,
// highlight/decoration treatment, entry animation and rhythm -- not just the
// same animation at a different speed.
export const CAPTION_PRESETS: CaptionPreset[] = [
  {
    id: "clean-pop",
    name: "Clean Pop",
    description: "White text, yellow highlights, small pop animation.",
    category: "minimal",
    style: { ...base, presetId: "clean-pop", fontFamily: "Inter", fontWeight: "semibold", fontSize: 60, stroke: "none", animation: "pop" },
  },
  {
    id: "bold-punch",
    name: "Bold Punch",
    description: "Big uppercase display type with a highlighter-style marker on emphasis.",
    category: "bold",
    style: {
      ...base,
      presetId: "bold-punch",
      fontFamily: "Anton",
      fontWeight: "extrabold",
      fontSize: 88,
      textCase: "uppercase",
      highlightColor: "#FFD400",
      stroke: "none",
      decoration: "marker",
      animation: "pop",
    },
  },
  {
    id: "kinetic-pulse",
    name: "Kinetic Pulse",
    description: "Fast, springy motion with a cyan highlight.",
    category: "kinetic",
    style: {
      ...base,
      presetId: "kinetic-pulse",
      fontFamily: "Space Grotesk",
      fontWeight: "bold",
      fontSize: 76,
      highlightColor: "#00E5FF",
      stroke: "none",
      animation: "bounce",
    },
  },
  {
    id: "editorial-serif",
    name: "Editorial",
    description: "Large elegant serif typography, minimal animation.",
    category: "editorial",
    style: {
      ...base,
      presetId: "editorial-serif",
      fontFamily: "Playfair Display",
      fontWeight: "semibold",
      fontSize: 70,
      textColor: "#FFFFFF",
      highlightColor: "#F2C879",
      stroke: "none",
      shadow: false,
      animation: "fade",
    },
  },
  {
    id: "marker-highlight",
    name: "Marker Highlight",
    description: "White text, animated highlighter-style background on key phrases.",
    category: "bold",
    style: {
      ...base,
      presetId: "marker-highlight",
      fontFamily: "DM Sans",
      fontWeight: "bold",
      fontSize: 66,
      highlightColor: "#FFEB3B",
      stroke: "none",
      decoration: "marker",
      animation: "slide-up",
    },
  },
  {
    id: "underline-sweep",
    name: "Underline Sweep",
    description: "Clean text with a colored underline beneath emphasized words.",
    category: "minimal",
    style: {
      ...base,
      presetId: "underline-sweep",
      fontFamily: "Manrope",
      fontWeight: "semibold",
      fontSize: 64,
      highlightColor: "#34D399",
      stroke: "none",
      decoration: "underline",
      animation: "fade",
    },
  },
  {
    id: "box-caption",
    name: "Box Caption",
    description: "Text inside a solid rounded background block.",
    category: "business",
    style: {
      ...base,
      presetId: "box-caption",
      fontFamily: "Inter",
      fontWeight: "semibold",
      fontSize: 56,
      background: "solid",
      stroke: "none",
      shadow: false,
      animation: "scale",
    },
  },
  {
    id: "business-minimal",
    name: "Business Minimal",
    description: "Professional typography, very low animation.",
    category: "business",
    style: {
      ...base,
      presetId: "business-minimal",
      fontFamily: "Inter",
      fontWeight: "medium",
      fontSize: 56,
      highlightColor: "#5AB8FF",
      stroke: "none",
      shadow: false,
      background: "semi-transparent",
      animation: "fade",
    },
  },
  {
    id: "creator-bold",
    name: "Creator Bold",
    description: "Large modern social-media style text, fast bounce.",
    category: "creator",
    style: {
      ...base,
      presetId: "creator-bold",
      fontFamily: "Bebas Neue",
      fontWeight: "bold",
      fontSize: 96,
      textCase: "uppercase",
      highlightColor: "#FF3D68",
      stroke: "none",
      animation: "bounce",
    },
  },
  {
    id: "gradient-bold",
    name: "Gradient Bold",
    description: "Animated gradient text fill, no outline.",
    category: "creator",
    style: {
      ...base,
      presetId: "gradient-bold",
      fontFamily: "Archivo Black",
      fontWeight: "extrabold",
      fontSize: 80,
      textColor: "#B26BFF",
      highlightColor: "#FF6EC7",
      stroke: "none",
      decoration: "gradient",
      animation: "pop",
    },
  },
  {
    id: "outline-punch",
    name: "Outline",
    description: "Thick black outline around bold uppercase type.",
    category: "bold",
    style: {
      ...base,
      presetId: "outline-punch",
      fontFamily: "Anton",
      fontWeight: "extrabold",
      fontSize: 84,
      textCase: "uppercase",
      stroke: "thick",
      shadow: false,
      animation: "pop",
    },
  },
  {
    id: "active-word",
    name: "Active Word",
    description: "Whole caption visible; the currently spoken word lights up.",
    category: "kinetic",
    style: {
      ...base,
      presetId: "active-word",
      fontFamily: "Outfit",
      fontWeight: "semibold",
      fontSize: 60,
      highlightColor: "#FFD400",
      stroke: "none",
      animation: "word-highlight",
      wordHighlightEnabled: true,
    },
  },
  {
    id: "hormozi-style",
    name: "Hormozi Style",
    description: "Large captions, strong word highlight, fast changes.",
    category: "bold",
    style: {
      ...base,
      presetId: "hormozi-style",
      fontFamily: "Anton",
      fontWeight: "extrabold",
      fontSize: 92,
      highlightColor: "#3CFF6E",
      stroke: "thick",
      shadow: true,
      position: "center",
      animation: "word-highlight",
      wordHighlightEnabled: true,
    },
  },
  {
    id: "condensed-impact",
    name: "Condensed Impact",
    description: "Tall condensed uppercase type, strong composition.",
    category: "bold",
    style: {
      ...base,
      presetId: "condensed-impact",
      fontFamily: "Barlow Condensed",
      fontWeight: "extrabold",
      fontSize: 90,
      textCase: "uppercase",
      highlightColor: "#FFD400",
      stroke: "medium",
      animation: "scale",
    },
  },
  {
    id: "modern-sans",
    name: "Modern Creator",
    description: "Rounded modern sans with a playful highlight pop.",
    category: "creator",
    style: {
      ...base,
      presetId: "modern-sans",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "bold",
      fontSize: 68,
      highlightColor: "#4ADE80",
      stroke: "none",
      animation: "scale",
    },
  },
  {
    id: "retro-condensed",
    name: "Retro",
    description: "Condensed serif-adjacent feel with a warm palette.",
    category: "editorial",
    style: {
      ...base,
      presetId: "retro-condensed",
      fontFamily: "Roboto Condensed",
      fontWeight: "bold",
      fontSize: 72,
      textColor: "#FDF3E3",
      highlightColor: "#E8734A",
      stroke: "none",
      animation: "slide-up",
    },
  },
  {
    id: "split-text",
    name: "Split Text",
    description: "Sentence splits into stacked lines, each entering in sequence.",
    category: "kinetic",
    style: {
      ...base,
      presetId: "split-text",
      fontFamily: "League Spartan",
      fontWeight: "bold",
      fontSize: 64,
      highlightColor: "#38BDF8",
      stroke: "none",
      animation: "slide-left",
      layout: "stacked",
    },
  },
  {
    id: "big-keyword",
    name: "Big Keyword",
    description: "Normal text, then the key number or phrase blows up huge.",
    category: "kinetic",
    style: {
      ...base,
      presetId: "big-keyword",
      fontFamily: "Archivo Black",
      fontWeight: "extrabold",
      fontSize: 56,
      highlightColor: "#FFD400",
      stroke: "none",
      animation: "pop",
      layout: "stacked",
    },
  },
  {
    id: "kinetic-stack",
    name: "Kinetic Stack",
    description: "Short word groups stack vertically as they're spoken.",
    category: "kinetic",
    style: {
      ...base,
      presetId: "kinetic-stack",
      fontFamily: "Urbanist",
      fontWeight: "extrabold",
      fontSize: 62,
      textCase: "uppercase",
      highlightColor: "#4ADE80",
      stroke: "none",
      animation: "slide-up",
      layout: "stacked",
    },
  },
  {
    id: "word-pop",
    name: "Word Pop",
    description: "One word at a time, full size, synced to speech.",
    category: "kinetic",
    style: {
      ...base,
      presetId: "word-pop",
      fontFamily: "Bricolage Grotesque",
      fontWeight: "extrabold",
      fontSize: 90,
      position: "center",
      highlightColor: "#FFD400",
      stroke: "none",
      animation: "pop",
      layout: "single-word",
    },
  },
  {
    id: "big-statement",
    name: "Big Statement",
    description: "Maximum size, centered, minimal per-word decoration.",
    category: "bold",
    style: {
      ...base,
      presetId: "big-statement",
      fontFamily: "Bricolage Grotesque",
      fontWeight: "extrabold",
      fontSize: 100,
      position: "center",
      highlightColor: "#FFD400",
      stroke: "none",
      animation: "pop",
    },
  },
  {
    id: "karaoke",
    name: "Karaoke",
    description: "Words fill in with color as they're spoken.",
    category: "kinetic",
    style: {
      ...base,
      presetId: "karaoke",
      fontFamily: "Rubik",
      fontWeight: "bold",
      fontSize: 62,
      highlightColor: "#FF9F1C",
      stroke: "none",
      animation: "word-highlight",
      wordHighlightEnabled: true,
    },
  },
  {
    id: "tamil-creator",
    name: "Tamil Creator",
    description: "Optimized for mixed Tamil and English captions.",
    category: "tamil",
    style: {
      ...base,
      presetId: "tamil-creator",
      fontFamily: "Baloo Two",
      fontWeight: "bold",
      fontSize: 66,
      highlightColor: "#FFD400",
      stroke: "medium",
      shadow: true,
      animation: "slide-up",
    },
  },
  {
    id: "tamil-minimal",
    name: "Tamil Minimal",
    description: "Clean Tamil-first captions for informational content.",
    category: "tamil",
    style: {
      ...base,
      presetId: "tamil-minimal",
      fontFamily: "Hind Madurai",
      fontWeight: "medium",
      fontSize: 56,
      highlightColor: "#5AB8FF",
      stroke: "none",
      shadow: false,
      animation: "fade",
    },
  },
];

export const DEFAULT_CAPTION_STYLE: CaptionStyle = CAPTION_PRESETS[0].style;
