import type { CaptionPreset, CaptionSettings, CaptionStyle } from "@/types";

export const DEFAULT_CAPTION_SETTINGS: CaptionSettings = {
  chunking: "medium",
  minWordsPerCaption: 4,
  maxWordsPerCaption: 7,
};

const base: Omit<CaptionStyle, "presetId"> = {
  fontFamily: "Inter",
  fontWeight: "bold",
  fontSize: 72,
  textAlign: "center",
  textColor: "#FFFFFF",
  highlightColor: "#FFD400",
  stroke: "medium",
  shadow: true,
  background: "none",
  textCase: "original",
  position: "bottom-center",
  animation: "pop",
  wordHighlightEnabled: false,
};

export const CAPTION_PRESETS: CaptionPreset[] = [
  {
    id: "minimal-clean",
    name: "Minimal Clean",
    description: "White text, yellow highlights, small pop animation.",
    style: {
      ...base,
      presetId: "minimal-clean",
      fontFamily: "Inter",
      fontWeight: "semibold",
      fontSize: 60,
      textColor: "#FFFFFF",
      highlightColor: "#FFD400",
      stroke: "none",
      shadow: true,
      animation: "pop",
    },
  },
  {
    id: "bold-creator",
    name: "Bold Creator",
    description: "Large bold text, centered, strong highlight.",
    style: {
      ...base,
      presetId: "bold-creator",
      fontFamily: "Poppins",
      fontWeight: "extrabold",
      fontSize: 84,
      textColor: "#FFFFFF",
      highlightColor: "#FF3B5C",
      stroke: "thick",
      shadow: true,
      position: "center",
      animation: "bounce",
    },
  },
  {
    id: "business",
    name: "Business",
    description: "Clean professional typography, minimal animation.",
    style: {
      ...base,
      presetId: "business",
      fontFamily: "Inter",
      fontWeight: "medium",
      fontSize: 56,
      textColor: "#FFFFFF",
      highlightColor: "#5AB8FF",
      stroke: "none",
      shadow: false,
      background: "semi-transparent",
      position: "bottom-center",
      animation: "fade",
    },
  },
  {
    id: "hormozi-style",
    name: "Hormozi Style",
    description: "Large captions, strong word highlight, fast changes.",
    style: {
      ...base,
      presetId: "hormozi-style",
      fontFamily: "Anton",
      fontWeight: "extrabold",
      fontSize: 92,
      textColor: "#FFFFFF",
      highlightColor: "#3CFF6E",
      stroke: "thick",
      shadow: true,
      position: "center",
      animation: "word-highlight",
      wordHighlightEnabled: true,
    },
  },
  {
    id: "tamil-creator",
    name: "Tamil Creator",
    description: "Optimized for mixed Tamil and English captions.",
    style: {
      ...base,
      presetId: "tamil-creator",
      fontFamily: "Poppins",
      fontWeight: "bold",
      fontSize: 68,
      textColor: "#FFFFFF",
      highlightColor: "#FFD400",
      stroke: "medium",
      shadow: true,
      position: "bottom-center",
      animation: "slide-up",
    },
  },
];

export const DEFAULT_CAPTION_STYLE: CaptionStyle = CAPTION_PRESETS[0].style;
